---
name: local
"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if rebuilding produce a dirty repo
        run: |
          npm install
          npx ncc build index.js
          if [[ -n $(git status --porcelain) ]]; then
            echo "Repo is dirty";
            git status --porcelain;
            exit 1;
          fi
        shell: bash

      - name: Test XVFB
        uses: ./
        with:
          run: echo 'Testing xvfb'

      - name: Test XVFB with working directory
        uses: ./
        with:
          working-directory: ./node_modules
          run: pwd

      - name: Test XVFB with options
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./
        with:
          options: -screen 0 1600x1200x24
          run: xrandr

      - name: Test XVFB with multiple commands
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: ./
        with:
          options: -screen 0 1600x1200x24
          run: |
            echo 'Testing xvfb'
            pwd
            xrandr
