---
# https://github.com/marketplace/actions/actions-tagger
name: release

"on":
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
